### ISSUE TITLE
highcharts cannot be shown in shinydashboard or shiny

### ISSUE THREAD

**Issue by cls3415** [ramnathv/rCharts#620]
Hi, 
I tried to use rCharts' hPlot and rendered into shinydashboard and regular shiny, but the graph doesn't not show. However, it is okay to use hPlot directly. The following is my code:

ui.R (for shinydashboard):
require(rCharts)
require(shiny)
require(shinydashboard)
ui <- dashboardPage(
  dashboardHeader(title = "Basic dashboard"),
  dashboardSidebar(),
  dashboardBody(
    # Boxes need to be put in a row (or column)
    fluidRow(
      box(showOutput("myChart", lib="highcharts"))
    )
  )
)

ui.R (for regular shiny):
require(rCharts)
shinyUI(pageWithSidebar(
  headerPanel("rCharts: Interactive Charts from R using polychart.js"),
  sidebarPanel(),
  mainPanel(
    showOutput("myChart", "highcharts")
  )
))

server.R:
require(rCharts)
server <- shinyServer(function(input, output) {
  output$myChart <- renderChart({
    p1 <- hPlot(Pulse ~ Height, data = MASS::survey, type = "scatter", group = "Exer")
    return(p1)
  })
})

**Comment by feiyangdou** [comment]
Try renderChart2.



**Comment by cls3415** [comment]
Thank-You feiyangdou. It works.
However, it seems like the figure size won't be adjusted according to shinydashboard's box. 
Any idea?

**Comment by feiyangdou** [comment]
I don't think it can be adjusted automatically. 
Two options:
* change the width and height of the chart by p1$chart(width = , height = )
* change the width and height of the box by box(...., height=, width)

**Comment by csese** [comment]
Hi, 
The way I have it working is by having the following lines:
p1$chart(height = ...)
p1$set(width = 100%)

Then it sets the width to fit the width of the boxes. 
It seems like it is not possible to specify % in the chart() commands whereas it works for the set commands. 
The reason why the height is in the chart() command is because it fits this value to all the charts available.
In my case (shiny app with multiple rcharts - highcharts), it sets the height for all the graphs when specified in p1$set!
